version: '3.6'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200' -c 'shared_buffers=512MB'
    environment:
      POSTGRES_DB: xdisx
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    network_mode: "host"
  contract-app:
    image: ghcr.io/magraul/contract-app:latest
    container_name: xdisx-contract-app
    environment:
      - SPRING_PROFILES_ACTIVE=local
    network_mode: "host"
    depends_on:
      - postgres
  customer-app:
    image: ghcr.io/magraul/customer-app:latest
    container_name: xdisx-customer-app
    environment:
      - SPRING_PROFILES_ACTIVE=local
    network_mode: "host"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local